apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: daprspike
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: frontend
      src: ./react-form
      ports:
        - name: http
          port: 8080
      publicPort: http
      authentication:
        oauth2:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis-oauth:6379
    - name: python-sub
      src: ./python-subscriber
      ports:
        - name: http
          port: 5001
    - name: node-sub
      src: ./node-subscriber
      ports:
        - name: http
          port: 3000
    - name: dotnet-sub
      src: ./csharp-subscriber
      variables:
        ASPNETCORE_URLS: http://*:5005
      ports:
        - name: http
          port: 5005
    - name: redis
      image: bitnami/redis:7.0
      secrets:
        - "REDIS_PASSWORD"
      ports:
        - name: http
          port: 6379
    - name: redis-oauth
      image: bitnami/redis:7.0
      secrets:
        - "REDIS_PASSWORD"
      ports:
        - name: http
          port: 6379
    - name: zipkin
      src: ./zipkin
      ports:
        - name: http
          port: 9411
     
      
