apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: daprspike
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: redis
      image: bitnami/redis:7.0
      secrets:
        - "REDIS_PASSWORD"
      ports:
        - name: http
          port: 6379
    - name: zipkin
      image: openzipkin/zipkin:2
      ports:
        - name: http
          port: 9411
     
      
