apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: daprspike-dev
spec:
  # secrets:
  #   scopes:
  #     - storeName: kubernetes
  #       allowedSecrets:
  #         - "redis-xyjsglhe"
  
  mtls:
    enabled: true
  logging:
    apiLogging:
      enabled: true
      omitHealthChecks: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
