apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dapr
  namespace: daprspike-dev
  labels:
    release: "kube-prometheus-stack"
spec:
  podMetricsEndpoints:
    - interval: 5s
      targetPort: 9090
      path: "/"
  namespaceSelector:
    matchNames:
      - "daprspike-dev"
  selector:
    matchLabels:
      radix-app: daprspike
    

    

    
    
    